import {
  hasAddressContext,
  hasPersonContext,
  isLikelyCardNumber,
  isLikelyPhone,
  isValidIPv4,
  isValidIPv6,
} from "@/lib/anonymizer/rules/helpers";
import type { AnonymizationRule } from "@/lib/anonymizer/rules/types";

export const universalRules: AnonymizationRule[] = [
  {
    id: "universal.person.ru_fio",
    type: "PERSON",
    pattern: /(?<![\p{L}])[А-ЯЁ][а-яё-]{2,}\s+[А-ЯЁ][а-яё-]{2,}\s+[А-ЯЁ][а-яё-]{2,}(?![\p{L}])/gu,
    priority: 76,
    confidenceBasis: "name-pattern+context",
    contextCheck: hasPersonContext,
  },
  {
    id: "universal.person.ru_fio_upper",
    type: "PERSON",
    pattern: /(?<![\p{L}])[А-ЯЁ-]{3,}\s+[А-ЯЁ-]{3,}\s+[А-ЯЁ-]{3,}(?![\p{L}])/gu,
    priority: 74,
    confidenceBasis: "name-pattern+context",
    contextCheck: hasPersonContext,
  },
  {
    id: "universal.person.ru_fullname_2parts",
    type: "PERSON",
    pattern: /(?<![\p{L}])[А-ЯЁ][а-яё-]{2,}\s+[А-ЯЁ][а-яё-]{2,}(?![\p{L}])/gu,
    priority: 71,
    confidenceBasis: "name-pattern+context",
    contextCheck: hasPersonContext,
  },
  {
    id: "universal.person.latin_fullname",
    type: "PERSON",
    pattern: /(?<![\p{L}])[A-Z][a-z-]{2,}\s+[A-Z][a-z-]{2,}\s+[A-Z][a-z-]{2,}(?![\p{L}])/gu,
    priority: 72,
    confidenceBasis: "name-pattern+context",
    contextCheck: hasPersonContext,
  },
  {
    id: "universal.person.latin_fullname_2parts",
    type: "PERSON",
    pattern: /(?<![\p{L}])[A-Z][a-z-]{2,}\s+[A-Z][a-z-]{2,}(?![\p{L}])/gu,
    priority: 69,
    confidenceBasis: "name-pattern+context",
    contextCheck: hasPersonContext,
  },
  {
    id: "universal.email",
    type: "EMAIL",
    pattern: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,
    priority: 90,
    confidenceBasis: "strict-format",
  },
  {
    id: "universal.phone",
    type: "PHONE",
    pattern: /\+?\d[\d\s().-]{8,}\d/g,
    priority: 85,
    confidenceBasis: "format",
    validator: isLikelyPhone,
  },
  {
    id: "universal.ipv4",
    type: "IP",
    pattern: /\b(?:\d{1,3}\.){3}\d{1,3}\b/g,
    priority: 87,
    confidenceBasis: "format+validator",
    validator: isValidIPv4,
  },
  {
    id: "universal.ipv6.full",
    type: "IP",
    pattern: /(?<![A-F0-9:])(?:[A-F0-9]{1,4}:){2,7}[A-F0-9]{1,4}(?![A-F0-9:])/gi,
    priority: 87,
    confidenceBasis: "format+validator",
    validator: isValidIPv6,
  },
  {
    id: "universal.ipv6.compressed",
    type: "IP",
    pattern: /(?<![A-F0-9:])(?:[A-F0-9]{1,4}:){0,7}::(?:[A-F0-9]{1,4}:){0,7}[A-F0-9]{0,4}(?![A-F0-9:])/gi,
    priority: 87,
    confidenceBasis: "format+validator",
    validator: isValidIPv6,
  },
  {
    id: "universal.address.ru.street_house",
    type: "ADDRESS",
    pattern: /\b(?:ул\.?|улица|пр-?кт|проспект|пер\.?|переулок|наб\.?|набережная|б-р|бульвар|ш\.?|шоссе|пл\.?|площадь)\s+[А-ЯЁA-Z][\p{L}\-.\s]{1,48}?,?\s*(?:д\.?|дом)\s*\d{1,4}[а-яa-z]?(?:\s*(?:кв\.?|квартира)\s*\d{1,4})?\b/giu,
    priority: 86,
    confidenceBasis: "strict-structure",
  },
  {
    id: "universal.address.de.street_house",
    type: "ADDRESS",
    pattern: /\b[A-ZÄÖÜ][\p{L}\-]{2,}(?:\s+[A-ZÄÖÜ][\p{L}\-]{2,})*\s+(?:straße|str\.?|weg|allee|platz|gasse|ring|ufer)\s+\d{1,4}[a-zA-Z]?\b/giu,
    priority: 86,
    confidenceBasis: "strict-structure",
  },
  {
    id: "universal.address.en.street_house",
    type: "ADDRESS",
    pattern: /\b\d{1,5}\s+[A-Za-z][A-Za-z.\- ]{1,50}\s(?:Street|St\.?|Road|Rd\.?|Avenue|Ave\.?|Lane|Ln\.?|Drive|Dr\.?|Boulevard|Blvd\.?|Court|Ct\.?|Place|Pl\.?|Way)\b/gi,
    priority: 84,
    confidenceBasis: "strict-structure",
  },
  {
    id: "universal.address.de.postcode_city",
    type: "ADDRESS",
    pattern: /\b\d{5}\s+[A-ZÄÖÜ][\p{L}\-]+(?:\s+[A-ZÄÖÜ][\p{L}\-]+){0,2}\b/gu,
    priority: 80,
    confidenceBasis: "postcode+locality+context",
    contextCheck: hasAddressContext,
  },
  {
    id: "universal.address.ru.postcode_city",
    type: "ADDRESS",
    pattern: /\b\d{6}\s*,?\s*(?:г\.?|город)\s+[А-ЯЁ][\p{L}\- ]{1,40}\b/gu,
    priority: 80,
    confidenceBasis: "postcode+locality+context",
    contextCheck: hasAddressContext,
  },
  {
    id: "universal.address.en.zip_city",
    type: "ADDRESS",
    pattern: /\b\d{5}(?:-\d{4})?\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,2}\b/g,
    priority: 78,
    confidenceBasis: "postcode+locality+context",
    contextCheck: hasAddressContext,
  },
  {
    id: "universal.card",
    type: "CARD",
    pattern: /\b(?:\d[ -]*?){13,19}\b/g,
    priority: 95,
    confidenceBasis: "format+luhn-or-shape",
    validator: isLikelyCardNumber,
  },
  {
    id: "universal.iban",
    type: "IBAN",
    pattern: /\b[A-Z]{2}\d{2}[A-Z0-9]{10,30}\b/g,
    priority: 88,
    confidenceBasis: "format",
  },
  {
    id: "universal.swiftbic",
    type: "SWIFT_BIC",
    pattern: /\b[A-Z]{6}[A-Z0-9]{2}(?:[A-Z0-9]{3})?\b/g,
    priority: 78,
    confidenceBasis: "format",
  },
  {
    id: "universal.account20",
    type: "ACCOUNT",
    pattern: /\b\d{20}\b/g,
    priority: 80,
    confidenceBasis: "length",
  },
  {
    id: "universal.date",
    type: "DATE",
    pattern: /\b(?:0?[1-9]|[12]\d|3[01])[./-](?:0?[1-9]|1[0-2])[./-](?:19\d{2}|20\d{2})\b/g,
    priority: 60,
    confidenceBasis: "format",
  },
  {
    id: "universal.date_iso_like",
    type: "DATE",
    pattern: /\b(?:19\d{2}|20\d{2})[./-](?:0?[1-9]|1[0-2])[./-](?:0?[1-9]|[12]\d|3[01])\b/g,
    priority: 60,
    confidenceBasis: "format",
  },
];
